syntax on
filetype plugin indent on

set t_Co=256
set laststatus=2
set ruler
set number

set expandtab
set shiftwidth=2
set softtabstop=2
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.log,*.aux,*.pdf
set runtimepath^=~/.vim/bundle/ctrlp.vim
colorscheme solarized
