syntax on
filetype plugin indent on

set t_Co=256
set laststatus=2
set ruler
set number

set expandtab
set textwidth=120
set shiftwidth=4
set softtabstop=4
set tabstop=4
set autoindent
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.log,*.aux,*.pdf
set background=dark
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
colorscheme elflord

call plug#begin(stdpath('data') . '/plugged')

Plug 'elmcast/elm-vim'

Plug 'ctrlpvim/ctrlp.vim'

call plug#end()
