#!/bin/sh

# Profile file. runs on login.

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave-browser"
export READER="zathura"
export FILE="vifm"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source "$HOME/.bashrc"

# [ "$(tty)" = "/dev/tty1" ] && ! pgrep -x i3 >/dev/null && exec startx
source "$HOME/.cargo/env"

. "$HOME/.local/bin/env"
